# So these ini files are divided into sections.
# it's pretty simple honestly, you can probably figure it out

[First Section]
# there's only three rules afaik for key names:
# 1. whitespace at the beginning and end of the key is ignored
# 2. keys cannot start with [
# 3. the key name stop when the first = is found

string value = Hello, world!

# sections can divide a program into logical bits like i2c addresses, encoder values, PID constants,
# etc.
# additionally, a simple model to adopt is to have each opmode to share one config file and have
# each auto and teleop mode to have their own section, with shared sections for values shared across
# opmodes

[Second Section]
# number values are really just doubles - you'll probably use these most often
# getNumber("number_value") or getd("number_value") works
# note that the "type" of the config value is actually determined by how the opmode decides to read
# a given key - for example, if you used secondSection.getInteger("number_value") the value would
# still be read, but it would be coerced to -5398

number_value = -5398.9971
other-number = 9872.3

integer.value = 125

# integers (but not numbers) can also be in hexadecimal notation. this is useful for i2c addresses
# please note that even so, long integers are not supported (unless you hack IniConfig.java)

hexInteger = 0x45
