[AutonomousOpMode]
# drivebase
drivebase.encRotCount = 1120
drivebase.maxCPS = 2640
driveStraight.gain = 0.015
#
# spool()
spool.power = 0.6
spool.timer = 1500
shoot.delay = 2000
#
# wallFollowWithGuard()
wallFollow.gain = 0.6
wallFollow.lineTimer = 1500
wallFollow.lineThreshold = 40
#
[Servos]
svoFeeder.initPosition = 0.981
svoLift.initPosition = 0
svoLift.medPosition = 0.4
svoLift.highPosition = 1
# revolver specific
svoFeeder.index = 0.013
svoFeeder.oneindex = 0.014
svoFeeder.twoindex = 0.026

[BeaconAutoOpMode]
line.threshold = 55
wall.threshold = 10
wall.closeThreshold = 8
line.followGain = 0.0012
line.followPower = 0.15
beacon.strafeOffset = 0.15

[TeleOp]
velocity = 0
joystickDeadzone = 0.1
drivebase.maxCPS = 2700
shooter.low = 0.22
shooter.med = 0.25
shooter.high = 0.3
shooter.super = 0.35
lift.upThreshold = 27
lift.downThreshold = 12
lift.encoderHigh = 0.2

[SanicAutonomous]
# distance away from wall the robot should stop
wallApproach.red = 25
wallApproach.blue = 25
# 
# number of rotations before switching to "approach" mode
farApproach.dist.red = 3.30
farApproach.dist.blue = 3.30
#
farApproach.wall.red = 22
farApproach.wall.blue = 18
#
nearApproach.dist.red = 2.4
nearApproach.dist.blue = 2.0
#
nearApproach.wall.red = 14
nearApproach.wall.blue = 18
#
shootPos.wall = 0.65
shootPos.comp = 0.3
#
shooter.power = 0.21
turn.degrees = -87
turn.gain = 0.008

[spicy autonomi]
#shooter power yo
shooter.power = 0.2
